export const consoleHtml = String.raw`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ATS MVP 控制台</title><style>
:root{font:15px/1.5 system-ui,sans-serif;color:#172033;background:#f5f7fb}body{margin:0}.wrap{max-width:1180px;margin:auto;padding:24px}header{display:flex;align-items:center;justify-content:space-between}h1{margin:0;font-size:26px}h2{font-size:17px;margin:0 0 12px}.grid{display:grid;grid-template-columns:330px 1fr;gap:18px;margin-top:20px}.card{background:#fff;border:1px solid #dbe2ef;border-radius:12px;padding:16px;box-shadow:0 1px 2px #dbe2ef}form{display:grid;gap:8px;margin:12px 0}input,textarea,select,button{font:inherit;padding:8px;border:1px solid #b9c4d6;border-radius:7px}textarea{min-height:80px}button{cursor:pointer;background:#155eef;color:white;border:0}button.secondary{background:#e8edf7;color:#172033}.list{display:grid;gap:7px}.item{border:1px solid #e1e6ef;border-radius:8px;padding:9px;cursor:pointer}.item.active{border-color:#155eef;background:#eff4ff}.muted{color:#667085;font-size:13px}.pill{display:inline-block;padding:2px 8px;border-radius:999px;background:#e9efff;color:#1649b8;font-size:12px}.actions{display:flex;gap:8px;flex-wrap:wrap}.notice{min-height:24px;padding:7px 10px;border-radius:7px;background:#edf7ef;color:#176638}.notice.error{background:#fff0f0;color:#b42318}pre{white-space:pre-wrap;word-break:break-word;background:#101828;color:#e4e7ec;padding:10px;border-radius:8px;max-height:230px;overflow:auto}@media(max-width:760px){.grid{grid-template-columns:1fr}}
</style></head><body><main class="wrap"><header><div><h1>ATS MVP 控制台</h1><div class="muted">仅本机回环地址提供服务 · 项目、计划、审批、执行与验收</div></div><button class="secondary" onclick="loadProjects()">刷新</button></header><div id="notice" class="notice">准备就绪。</div><div class="grid"><aside class="card"><h2>项目与任务</h2><form id="projectForm"><input name="name" required placeholder="新项目名称"><button>创建项目</button></form><div id="projects" class="list"></div><hr><form id="taskForm"><input name="title" required placeholder="新任务标题"><button>添加到当前项目</button></form><div id="tasks" class="list muted">先选择一个项目</div></aside><section class="card"><div id="detail" class="muted">选择任务后，在这里创建计划、审批、执行并验收。</div></section></div></main>
<script>
let selectedProject,selectedTask;
const $=s=>document.querySelector(s); const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function note(message,error=false){const n=$('#notice');n.textContent=message;n.className='notice'+(error?' error':'')}
async function api(path, options={}){const r=await fetch(path,{headers:{'content-type':'application/json'},...options});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'请求失败');return d}
async function loadProjects(){try{const projects=await api('/projects');$('#projects').innerHTML=projects.length?projects.map(p=>'<div class="item '+(p.id===selectedProject?'active':'')+'" onclick="pickProject(\''+p.id+'\')"><b>'+escape(p.name)+'</b><div class="muted">'+escape(p.created_at)+'</div></div>').join(''):'<span class="muted">尚无项目</span>';if(selectedProject)await loadTasks()}catch(e){note(e.message,true)}}
async function pickProject(id){selectedProject=id;selectedTask=null;await loadProjects();}
async function loadTasks(){try{const tasks=await api('/projects/'+selectedProject+'/tasks');$('#tasks').innerHTML=tasks.length?tasks.map(t=>'<div class="item '+(t.id===selectedTask?'active':'')+'" onclick="pickTask(\''+t.id+'\')"><b>'+escape(t.title)+'</b><div><span class="pill">'+escape(t.status)+'</span></div></div>').join(''):'<span>尚无任务</span>';if(selectedTask)await loadDetail()}catch(e){note(e.message,true)}}
async function pickTask(id){selectedTask=id;await loadTasks();}
async function loadDetail(){try{const d=await api('/tasks/'+selectedTask+'/console');const t=d.task,p=d.plan,e=d.executions[0];$('#detail').innerHTML='<h2>'+escape(t.title)+'</h2><p><span class="pill">任务：'+escape(t.status)+'</span></p><h2>计划与审批</h2>'+(p?'<p><span class="pill">计划：'+escape(p.status)+'</span></p><pre>'+escape(p.body)+'</pre><div class="actions">'+(p.status==='draft'?'<button onclick="act(\'/plans/'+p.id+'/submit\',{})">提交计划</button>':'')+(p.status==='submitted'?'<button onclick="act(\'/plans/'+p.id+'/approve\',{actor:\'reviewer\'})">批准计划</button><button class="secondary" onclick="act(\'/plans/'+p.id+'/reject\',{actor:\'reviewer\'})">拒绝计划</button>':'')+'</div>':'<form id="planForm"><textarea name="body" required placeholder="描述执行计划"></textarea><button>生成计划</button></form>')+'<h2 style="margin-top:18px">执行与验收</h2><p>'+(e?'<span class="pill">执行：'+escape(e.status)+'</span> '+escape(e.provider):'尚未执行')+'</p><div class="actions">'+(t.status==='ready'?'<button onclick="act(\'/tasks/'+t.id+'/executions\',{provider:\'noop\'})">开始执行</button>':'')+(e&&e.status==='active'?'<button onclick="act(\'/executions/'+e.id+'/finish\',{})">完成执行</button>':'')+(t.status==='awaiting_acceptance'?'<button onclick="act(\'/tasks/'+t.id+'/accept\',{actor:\'reviewer\'})">验收通过</button><button class="secondary" onclick="act(\'/tasks/'+t.id+'/reject\',{actor:\'reviewer\'})">验收驳回</button>':'')+'</div><h2 style="margin-top:18px">审计记录</h2><pre>'+escape(JSON.stringify(d.audit,null,2))+'</pre>';const f=$('#planForm');if(f)f.onsubmit=async ev=>{ev.preventDefault();await act('/tasks/'+t.id+'/plans',{body:new FormData(f).get('body')})}}catch(e){note(e.message,true)}}
async function act(path,body){try{await api(path,{method:'POST',body:JSON.stringify(body)});note('操作已完成。');await loadDetail();await loadTasks()}catch(e){note('操作未执行：'+e.message,true)}}
$('#projectForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/projects',{method:'POST',body:JSON.stringify({name:new FormData(e.target).get('name')})});e.target.reset();selectedProject=d.id;note('项目已创建。');await loadProjects()}catch(x){note(x.message,true)}};
$('#taskForm').onsubmit=async e=>{e.preventDefault();if(!selectedProject)return note('请先选择或创建项目。',true);try{const d=await api('/projects/'+selectedProject+'/tasks',{method:'POST',body:JSON.stringify({title:new FormData(e.target).get('title')})});e.target.reset();selectedTask=d.id;note('任务已创建。');await loadTasks()}catch(x){note(x.message,true)}};loadProjects();
</script></body></html>`;
